### ISSUE TITLE
Support for SASL 

### ISSUE THREAD

**Issue by Hiteshkikani** [GSLabDev/pepper-box#6] opened 2017-11-15 08:22 UTC
I am trying to connect IBM message hub which is based on Kafka 0.10.2.1 through pepper-box plugin.
It uses SASL_Plaintext protocol. So in PepperBox Kafka sampler, i am setting attributes as below.
security.protocol=SASL_PLAINTEXT
java.security.auth.login.config= "Path to my jaas.conf"

When I run the script i get error "org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode." even i have already passed jaas.conf file.

I am not sure if SASL is already supported by pepper-box and I am missing something.

Your help is appreciated.

**Comment by satishbhor** [comment] 2017-11-15 08:27
@Hiteshkikani  Are you using standalone jar or using as jmeter plugin ?

**Comment by Hiteshkikani** [comment] 2017-11-15 08:35
@satishbhor I have passed absolute path. I am using it as jmeter plugin

**Comment by satishbhor** [comment] 2017-11-15 08:47
@Hiteshkikani did you marked property (kerberos.auth.enabled) to yes ?

**Comment by Hiteshkikani** [comment] 2017-11-15 08:52
kerberos.auth.enabled was set to "NO". I tried setting it to "Yes" and now i see error as "Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.kafka.common.security.plain.PlainLoginModule
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74) ~[pepper-box-1.0.jar:?]"

Just to confirm my JAAS file contains
"KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="name of the user"
    password="password for the user";
};"

**Comment by satishbhor** [comment] 2017-11-15 09:01
@Hiteshkikani  could u please add following to maven dependencies and try by building jar again
` <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka_2.11</artifactId>
        <version>${kafka.version}</version>
</dependency>
`

**Comment by Hiteshkikani** [comment] 2017-11-15 09:06
@satishbhor this dependency was already there in pom file when i built jar

**Comment by satishbhor** [comment] 2017-11-15 09:07
@Hiteshkikani corrected dependency could u please change it. I mean to say org.apache.kafka.common.security.plain.PlainLoginModule class is in kafka-client dependency that is in test scope. could u please add 
`<dependency> 
<groupId>org.apache.kafka</groupId>
<artifactId>kafka-clients</artifactId>
<version>${kafka.version}</version> 
</dependency>`

**Comment by Hiteshkikani** [comment] 2017-11-15 09:51
Tried adding dependency but still same error..please refer attached files for configuration, pom and logs
[files.zip](https://github.com/GSLabDev/pepper-box/files/1474137/files.zip)

**Comment by satishbhor** [comment] 2017-11-15 10:18
@Hiteshkikani let me reproduce issue

**Comment by satishbhor** [comment] 2017-11-15 12:03
@Hiteshkikani I could reproduce issue, issue is occurred due to property 'sasl.mechanism', could you please take latest pull and try with sasl.mechanism=PLAIN as custom property in JMeter?

**Comment by Hiteshkikani** [comment] 2017-11-15 12:58
i have pulled latest source files & built jar but i am confused with sasl.mechanism=PLAIN as custom property.
Can you clarify how can is set sasl.mechanism=PLAIN as custom property?

**Comment by satishbhor** [comment] 2017-11-15 13:02
![screenshot from 2017-11-15 18-30-41](https://user-images.githubusercontent.com/538910/32837367-4972021a-ca33-11e7-8f0c-8e9a795d1ed0.png)
Add property on jmeter sampler with prefix '_'

**Comment by Hiteshkikani** [comment] 2017-11-15 13:09
I tried adding parameter.
![image](https://user-images.githubusercontent.com/7577959/32837555-af84561a-ca16-11e7-9725-d29df1b0cadb.png)
But when i save the test plan or replay, added parameter (_sasl.mechanism) gets deleted automatically.
![image](https://user-images.githubusercontent.com/7577959/32837616-e0926ea4-ca16-11e7-845c-7210d7934265.png)

**Comment by satishbhor** [comment] 2017-11-15 13:23
I did quick fix for sasl.mechanism take pull and build again. default value is GSSAPI change it to PLAIN

**Comment by Hiteshkikani** [comment] 2017-11-15 13:36
no luck..still same error

**Comment by satishbhor** [comment] 2017-11-15 13:37
could u please share jmeter.log file?

**Comment by Hiteshkikani** [comment] 2017-11-15 13:43
Sure. Here it is

[jmeter.zip](https://github.com/GSLabDev/pepper-box/files/1474874/jmeter.zip)

**Comment by satishbhor** [comment] 2017-11-16 06:03
@Hiteshkikani looks like you have deployed kafkameter in jmeter as well thats why classes are conflicting with pepper-box


```
Caused by: javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.kafka.common.security.plain.PlainLoginModule
	at javax.security.auth.login.LoginContext.invoke(Unknown Source) ~[?:1.8.0_151]
	at javax.security.auth.login.LoginContext.access$000(Unknown Source) ~[?:1.8.0_151]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) ~[?:1.8.0_151]
	at javax.security.auth.login.LoginContext$4.run(Unknown Source) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at javax.security.auth.login.LoginContext.invokePriv(Unknown Source) ~[?:1.8.0_151]
	at javax.security.auth.login.LoginContext.login(Unknown Source) ~[?:1.8.0_151]
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:298) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:80) ~[kafkameter-0.2.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[kafkameter-0.2.3.jar:?]
```

**Comment by Hiteshkikani** [comment] 2017-11-16 07:35
ah my bad..I removed kafkameter jars from jmeter. Still i am getting same error..logs are attached here..
For you information, i am using jmeter 3.2
Did it work for you after you reproduced the issue? If yes can you send me jar file you are using?
[jmeter (2).zip](https://github.com/GSLabDev/pepper-box/files/1477679/jmeter.2.zip)

**Comment by satishbhor** [comment] 2017-11-16 09:04
@Hiteshkikani Looks like u are building jar with default Kafka version which is 0.9.0.1(mvn clean install and not mvn clean install -Dkafka.version=0.10.2.1) and it does not have plain-text login module. Due to test failures for new kafka version I have created new branch 'jmeter3.2_kafka10.2' for new Kafka version and jmeter please take new branch code and try with it.

**Comment by Hiteshkikani** [comment] 2017-11-16 10:09
@satishbhor You Rock!!! It worked and now user is able to login but it failing now in sneding a message. Please refer jmeter logs. In logs, 1st i tried without  Kafka PlainText Load Generator Config and in 2nd iteration i tried with Kafka PlainText Load Generator Config.

Appreciate your kind help.
[jmeter (3).zip](https://github.com/GSLabDev/pepper-box/files/1478124/jmeter.3.zip)

**Comment by satishbhor** [comment] 2017-11-16 10:24
@Hiteshkikani one of the Pepper-box requirement is JDK instead of JRE. Please make sure that you have JDK installed and not just JRE.

**Comment by Hiteshkikani** [comment] 2017-11-16 11:16
I confirmed and it is jdk 8.

![image](https://user-images.githubusercontent.com/7577959/32888536-3751b0c4-cad0-11e7-98ef-cc83cb071dfc.png)

**Comment by satishbhor** [comment] 2017-11-16 11:42
Now days window comes with built-in jre and its path is set in environment variables. Please make sure that no other java path is set than above mentioned path.

**Comment by Hiteshkikani** [comment] 2017-11-16 12:42
Re-checked. Could not find other java anywhere in  environment variables

**Comment by Nachiket90** [comment] 2017-11-16 12:50
@Hiteshkikani Can you please paste output of ```where java``` command?

**Comment by Hiteshkikani** [comment] 2017-11-16 13:05
C:\Windows\system32>where java
C:\ProgramData\Oracle\Java\javapath\java.exe
C:\Program Files\Java\jdk1.8.0_151\bin\java.exe

**Comment by satishbhor** [comment] 2017-11-16 13:34
@Hiteshkikani  thats the issue you will have to remove first java from path.

**Comment by Hiteshkikani** [comment] 2017-11-16 13:52
yippee...it worked..thank you so much  for your help :+1: :100:

**Comment by vinodborole** [comment] 2017-11-16 13:58
@Hiteshkikani If you are satisfied, can you please close the issue?

**Closed** 2017-11-16 14:00 UTC
Labels: help wanted

**Comment by userseljm999** [comment] 2018-06-07 21:17
I took Jmeter 3.2 and Kfka 0.10.2 branch built new Jar file. WIth that i'm getting below error

2018-06-07 16:03:15,462 INFO o.a.z.ZooKeeper: Initiating client connection, connectString=165.237.41.4:2181,165.237.41.5:2181,165.237.41.6:2181 sessionTimeout=10000 watcher=null
2018-06-07 16:03:15,501 WARN o.a.z.ClientCnxn: SASL configuration failed: javax.security.auth.login.LoginException: Unable to obtain password from user
 Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it.
2018-06-07 16:03:15,502 INFO o.a.z.ClientCnxn: Opening socket connection to server 165.237.41.4/165.237.41.4:2181
2018-06-07 16:03:15,502 ERROR o.a.z.ClientCnxn: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530) [pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505) [pepper-box-1.0.jar:?]
2018-06-07 16:03:15,563 INFO o.a.z.ClientCnxn: Socket connection established to 165.237.41.4/165.237.41.4:2181, initiating session
2018-06-07 16:03:15,624 INFO o.a.z.ClientCnxn: Session establishment complete on server 165.237.41.4/165.237.41.4:2181, sessionid = 0x163b76b818e02c7, negotiated timeout = 10000
2018-06-07 16:03:15,624 ERROR o.a.z.ClientCnxn: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530) [pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505) [pepper-box-1.0.jar:?]
2018-06-07 16:03:15,695 ERROR c.g.p.s.PepperBoxKafkaSampler: Failed to get broker information
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1532) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1560) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.getBrokerServers(PepperBoxKafkaSampler.java:207) [pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:105) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
2018-06-07 16:03:15,713 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	acks = 1
	batch.size = 16384
	block.on.buffer.full = false
	bootstrap.servers = [165.237.41.4:6668, 165.237.41.5:6668, 165.237.41.6:6668, 165.237.41.7:6668, 165.237.41.8:6668]
	buffer.memory = 33554432
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.fetch.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = vod-kafka
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = SASL_SSL
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	timeout.ms = 30000
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2018-06-07 16:03:15,733 INFO o.a.k.c.p.KafkaProducer: Closing the Kafka producer with timeoutMillis = 0 ms.
2018-06-07 16:03:15,734 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:342) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:191) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:150) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Unable to obtain password from user

	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:94) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:93) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:84) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:305) ~[pepper-box-1.0.jar:?]
	... 7 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain password from user

	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:897) ~[?:1.8.0_51]
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760) ~[?:1.8.0_51]
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_51]
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:58) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:109) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:55) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:89) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:86) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:93) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:84) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:305) ~[pepper-box-1.0.jar:?]
	... 7 more
2018-06-07 16:03:15,735 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2018-06-07 16:03:15,735 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2018-06-07 16:03:15,735 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2018-06-07 16:03:15,735 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.protocol.java.sampler.JavaSampler@399f50c0
java.lang.NullPointerException: null
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.teardownTest(PepperBoxKafkaSampler.java:193) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:293) ~[ApacheJMeter_java.jar:3.2 r1790748]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:498) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
2018-06-07 16:03:15,735 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by seema30mehra** [comment] 2020-01-16 17:05
I m still not able to set sasl_mechanism as PLAIN..

**Comment by katekrov** [comment] 2020-05-07 12:39
Hi, could someone help me? I would appreciate any help

I need to use: 
sasl.mechanism = PLAIN
security.protocol = SASL_SSL

and I have in logs:

sasl.mechanism = GSSAPI
security.protocol = SASL_SSL

**Comment by rathjagan05** [comment] 2020-07-23 12:51
my java request is getting passed ,but topic on kafka is not getting created


2020-07-23 18:15:24,759 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-07-23 18:15:24,761 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-07-23 18:15:24,762 INFO o.a.j.p.j.t.JavaTest: Created class: com.gslab.pepper.sampler.PepperBoxKafkaSampler. Uses tearDownTest: true
2020-07-23 18:15:24,762 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-07-23 18:15:24,896 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : SAMS
2020-07-23 18:15:24,897 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group SAMS.
2020-07-23 18:15:24,898 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-07-23 18:15:24,898 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=0 perThread=0.0 delayedStart=false
2020-07-23 18:15:24,899 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-07-23 18:15:24,900 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-07-23 18:15:24,900 INFO o.a.j.t.JMeterThread: Thread started: SAMS 1-1
2020-07-23 18:15:25,201 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [10.159.22.77:3010]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = PLAINTEXT
	retries = 0
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

2020-07-23 18:15:25,220 INFO o.a.k.c.u.AppInfoParser: Kafka version : 0.9.0.1
2020-07-23 18:15:25,221 INFO o.a.k.c.u.AppInfoParser: Kafka commitId : 23c69d62a0cabf06
2020-07-23 18:15:25,435 INFO o.a.j.t.JMeterThread: Thread is done: SAMS 1-1
2020-07-23 18:15:25,435 INFO o.a.j.t.JMeterThread: Thread finished: SAMS 1-1
2020-07-23 18:15:25,436 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-07-23 18:15:25,437 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.protocol.java.sampler.JavaSampler@7c44161d
java.lang.NullPointerException: null
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.teardownTest(PepperBoxKafkaSampler.java:155) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:293) ~[ApacheJMeter_java.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
2020-07-23 18:15:25,438 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by rathjagan05** [comment] 2020-07-23 12:52
@Hiteshkikani :could you please help

**Comment by radev-dev** [comment] 2020-08-26 02:29
Can somebody help me resolving below issue I am getting? I am getting this issue while posting message to Kafka broker. Message is not getting posted to kafka broker.

jmeter version: **apache-jmeter-4.0**
kafka: **kafka_2.11-1.0.1**

ERROR c.g.p.s.PepperBoxKafkaSampler: **Failed to send message**
java.lang.NullPointerException: null
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.runTest(PepperBoxKafkaSampler.java:138) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) [ApacheJMeter_java.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:490) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250) [ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
 ERROR o.a.j.t.JMeterThread: **Error while processing sampler: 'Java Request'.**
java.lang.NullPointerException: null
	at org.apache.jmeter.samplers.SampleResult.setResponseData(SampleResult.java:721) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.runTest(PepperBoxKafkaSampler.java:144) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:490) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416) [ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250) [ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
